// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCategory = `-- name: AddCategory :exec
INSERT INTO categories (id, name, description)
VALUES ($1, $2, $3)
`

type AddCategoryParams struct {
	ID          string
	Name        string
	Description pgtype.Text
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) error {
	_, err := q.db.Exec(ctx, addCategory, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteCategoryById = `-- name: DeleteCategoryById :execresult
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategoryById(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCategoryById, id)
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT
  id,
  name,
  description
FROM categories
WHERE id <> 'DEF'
`

type GetAllCategoriesRow struct {
	ID          string
	Name        string
	Description pgtype.Text
}

func (q *Queries) GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT
  id,
  name,
  description
FROM categories
WHERE id = $1
`

type GetCategoryByIdRow struct {
	ID          string
	Name        string
	Description pgtype.Text
}

func (q *Queries) GetCategoryById(ctx context.Context, id string) (GetCategoryByIdRow, error) {
	row := q.db.QueryRow(ctx, getCategoryById, id)
	var i GetCategoryByIdRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const updateCategoryById = `-- name: UpdateCategoryById :execresult
UPDATE categories
SET
  name = $1,
  description = $2,
  updated_at = now()
WHERE id = $3
`

type UpdateCategoryByIdParams struct {
	Name        string
	Description pgtype.Text
	ID          string
}

func (q *Queries) UpdateCategoryById(ctx context.Context, arg UpdateCategoryByIdParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateCategoryById, arg.Name, arg.Description, arg.ID)
}
