// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProduct = `-- name: AddProduct :exec
INSERT INTO products (name, price, stock, category_id)
VALUES ($1, $2, $3, $4)
`

type AddProductParams struct {
	Name       string
	Price      pgtype.Numeric
	Stock      int16
	CategoryID string
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) error {
	_, err := q.db.Exec(ctx, addProduct,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
	)
	return err
}

const deleteProductById = `-- name: DeleteProductById :execresult
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProductById(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteProductById, id)
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
  p.id,
  p.name,
  p.price,
  p.stock,
  c.name AS category_name,
  c.description AS category_description
FROM products p
JOIN categories c ON p.category_id = c.id
`

type GetAllProductsRow struct {
	ID                  int64
	Name                string
	Price               pgtype.Numeric
	Stock               int16
	CategoryName        string
	CategoryDescription pgtype.Text
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CategoryName,
			&i.CategoryDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT
  p.id,
  p.name,
  p.price,
  p.stock,
  c.name AS category_name,
  c.description AS category_description
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.id = $1
`

type GetProductByIdRow struct {
	ID                  int64
	Name                string
	Price               pgtype.Numeric
	Stock               int16
	CategoryName        string
	CategoryDescription pgtype.Text
}

func (q *Queries) GetProductById(ctx context.Context, id int64) (GetProductByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryName,
		&i.CategoryDescription,
	)
	return i, err
}

const updateProductById = `-- name: UpdateProductById :execresult
UPDATE products
SET
  name = $1,
  price = $2,
  stock = $3,
  category_id = $4,
  updated_at = now()
WHERE id = $5
`

type UpdateProductByIdParams struct {
	Name       string
	Price      pgtype.Numeric
	Stock      int16
	CategoryID string
	ID         int64
}

func (q *Queries) UpdateProductById(ctx context.Context, arg UpdateProductByIdParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateProductById,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
		arg.ID,
	)
}
