// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddCategory(ctx context.Context, arg AddCategoryParams) error
	AddProduct(ctx context.Context, arg AddProductParams) error
	DeleteCategoryById(ctx context.Context, id string) error
	DeleteProductById(ctx context.Context, id int64) error
	GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetCategoryById(ctx context.Context, id string) (GetCategoryByIdRow, error)
	GetProductById(ctx context.Context, id int64) (GetProductByIdRow, error)
	UpdateCategoryById(ctx context.Context, arg UpdateCategoryByIdParams) error
	UpdateProductById(ctx context.Context, arg UpdateProductByIdParams) error
}

var _ Querier = (*Queries)(nil)
